### ISSUE TITLE
Tekst-dingetjes

### ISSUE THREAD

**Issue by vasilisvg** [soraya2/css-to-the-rescue#10]
- Justified tekst ziet er mooi uit, maar het leest niet lekker. Het is beter om links uit te lijnen. 
- Heb je getest of dat uitklappen van die paragrafen bij de media-items werkt? Probeer het eens uit met een paar mensen en vraag ze om te vertellen of ze snappen wat er precies gebeurt.

**Comment by soraya2** [comment]
Fixed it in my end assignment bij giving the user an intro and putting a link to the actual detail page.
