### ISSUE TITLE
# Media item

### ISSUE THREAD

**Issue by vasilisvg** [soraya2/css-to-the-rescue#3]
- Het media-item wordt vaak gebruikt op homepages van bijvoorbeeld een nieuwssite. Dan is het handig als het in z'n geheel klikbaar is. En ja, dat kan ook zonder de HTML aan te passen (-:
- Je hebt nu maar een visuele variant gemaakt van het media-element. Maar er zijn flink wat verschillende manieren te bedenken waarop je dit kunt laten zien. Zie bijvoorbeeld de homepage van [The Guardian](https://www.theguardian.com/international) of de linkerkolom van [de Volkskrant](http://www.volkskrant.nl). Kijk eens of je net zo'n lijst kan maken waarbij de eerste er anders uit ziet dan de rest.

**Comment by soraya2** [comment]
Fixed this in my end assignment by using css grid layout. The first media item is the most important and the biggest.
